abstract class CacheableInterface {
  toJson();
  String getChecksum();
  String joinData();
}

abstract class Cacheable implements CacheableInterface {
  String id;
  Cacheable({required this.id});
  @override
  toJson() => throw UnimplementedError();
  //GENERATED BY CHATGPT
  @override
  getChecksum() {
    int _fnv1aHash(String data) {
      const int fnvPrime = 0x01000193;
      int hash = 0x811c9dc5;

      for (int i = 0; i < data.length; i++) {
        hash ^= data.codeUnitAt(i);
        hash = (hash * fnvPrime) & 0xFFFFFFFF;
      }
      return hash;
    }

    int hash = _fnv1aHash(this.joinData());
    return hash.toRadixString(16).padLeft(8, '0');
  }

  @override
  joinData() => throw UnimplementedError();
}

abstract class CacheableFactory<T extends Cacheable> {
  T fromJson(Map<String, dynamic> json) => throw UnimplementedError();
}
