import 'dart:convert';
import 'package:build_stats_flutter/model/entity/checklist.dart';
import 'package:build_stats_flutter/model/storage/data_sync/data_connection.dart';
import 'package:build_stats_flutter/model/storage/local_storage/file_access.dart';
import 'package:build_stats_flutter/model/storage/item_cache.dart';
import 'package:build_stats_flutter/resources/app_strings.dart';
import 'package:localstorage/localstorage.dart';

class ChecklistCache {
  //final Map<int, Item?> _itemCache = {};
  static Future<Checklist?> GetChecklistById(String id) async {
    Checklist? checklist;
    String? checklistJson = localStorage.getItem(id);
    if (checklistJson != null) {
      checklist = Checklist.fromJson(jsonDecode(checklistJson));
    } else {
      checklist = await LoadChecklistById(id);
    }
    if (checklist != null) {
      checklist.items = [];
      for (var x in checklist.itemIds) {
        await ItemCache.GetItemById(x)
            .then((item) => {checklist?.items.add(item!)});
      }
    }
    return checklist;
  }

  //Initially Generated by CHATGPT
  static Future<Checklist?> LoadChecklistById(String id) async {
    List<Checklist> checklists = [];
    if (!(await DataConnection.checkConnection())) {
      // Get the directory of the application documents
      final file = await FileAccess.getDataFile(
          ChecklistFileString); //TODO: need to change to dependency injection when I know how.

      // Check if the file exists
      if (await file.exists()) {
        // Read the JSON file
        String jsonString = await file.readAsString();

        // Decode the JSON string into a List of dynamic objects
        List<dynamic> jsonData = jsonDecode(jsonString);

        // Convert the dynamic objects into a List of Checklist objects
        checklists = jsonData.map((json) => Checklist.fromJson(json)).toList();
      }
    }

    if (checklists.isEmpty) {
      return null;
    }

    // Traverse the hierarchy to find the Checklist with the given ID
    for (Checklist checklist in checklists) {
      if (localStorage.getItem(checklist.id) == null) {
        localStorage.setItem(checklist.id, jsonEncode(checklist.toJson()));
      }
      if (checklist.id == id) {
        return checklist;
      }
    }
    // If the item is not found, return null
    return null;
  }

  static Future<Null> StoreChecklist(Checklist checklist) async {
    localStorage.setItem(checklist.id, jsonEncode(checklist.toJson()));
    await SaveChecklist(checklist);
  }

  //Initially Generated by CHATGPT
  static Future<Null> SaveChecklist(Checklist checklist) async {
    // Get the directory of the application documents
    final file = await FileAccess.getDataFile(
        ChecklistFileString); //TODO: need to change to dependency injection when I know how.

    List<Checklist> checklists = [];

    // Check if the file exists
    if (await file.exists()) {
      // Read the JSON file
      String jsonString = await file.readAsString();

      // Decode the JSON string into a List of dynamic objects
      List<dynamic> jsonData = jsonDecode(jsonString);

      // Convert the dynamic objects into a List of Checklist objects
      checklists = jsonData.map((json) => Checklist.fromJson(json)).toList();
    }

    // Flag to check if the checklist was saved
    // Traverse the hierarchy to find where to save the checklist
    int checklistIndex = checklists.indexWhere((i) => i.id == checklist.id);
    if (checklistIndex != -1) {
      checklists[checklistIndex] = checklist;
    } else {
      checklists.add(checklist);
    }
    // Encode the checklists back to JSON and save to the file
    String updatedJson =
        jsonEncode(checklists.map((checklist) => checklist.toJson()).toList());
    await FileAccess.SaveDataFile(ChecklistFileString, updatedJson);
  }
}
