import 'dart:convert';
import 'package:build_stats_flutter/model/Domain/ServiceInterface/data_connection_service.dart';
import 'package:build_stats_flutter/model/entity/item.dart';
import 'package:build_stats_flutter/model/Domain/ServiceInterface/cache_service.dart';
import 'package:build_stats_flutter/model/storage/data_sync/data_connection.dart';
import 'package:build_stats_flutter/model/storage/local_storage/file_access.dart';
import 'package:build_stats_flutter/resources/app_strings.dart';
import 'package:localstorage/localstorage.dart';

class ItemCache implements CacheService<Item> {
  final DataConnectionService<Item> _dataConnectionService;
  ItemCache(this._dataConnectionService);

  @override
  Future<Item?> getById(String key) async {
    Item? item;
    String? itemJson = localStorage.getItem(key);
    if (itemJson != null) {
      item = Item.fromJson(jsonDecode(itemJson));
    } else {
      item = await load(key);
    }
    return item;
  }

  @override
  Future<void> delete(String key) {
    // TODO: implement delete
    throw UnimplementedError();
  }

  @override
  Future<Item> load(String key) {
    // TODO: implement load
    throw UnimplementedError();
  }

  @override
  Future<void> save(String key, value) {
    // TODO: implement save
    throw UnimplementedError();
  }

  @override
  Future<void> store(String key, value) {
    // TODO: implement store
    throw UnimplementedError();
  }

  static Future<List<Item>> _getItems() async {
    List<Item> items = [];
    if (!(await DataConnection.CheckConnection())) {
      String jsonString = await FileAccess.ReadJsonDataFile(ItemFileString);
      if (jsonString.isNotEmpty) {
        List<dynamic> jsonData = jsonDecode(jsonString);
        items = jsonData.map((json) => Item.fromJson(json)).toList();
      }
    }
    return items;
  }

  //Initially Generated by CHATGPT
  static Future<Item?> LoadItemById(String id) async {
    List<Item> items = await _getItems();
    if (items.isEmpty) {
      return null;
    }

    // Traverse the hierarchy to find the Item with the given ID
    for (Item item in items) {
      if (localStorage.getItem(item.id) == null) {
        localStorage.setItem(item.id, jsonEncode(item.toJson()));
      }
      if (item.id == id) {
        return item;
      }
    }
    // If the item is not found, return null
    return null;
  }

  static Future<Null> StoreItem(Item item) async {
    localStorage.setItem(item.id, jsonEncode(item.toJson()));
    await SaveItem(item);
  }

  //Initially Generated by CHATGPT
  static Future<Null> SaveItem(Item item) async {
    List<Item> items = await _getItems();
    // Flag to check if the item was saved
    // Traverse the hierarchy to find where to save the item
    int itemIndex = items.indexWhere((i) => i.id == item.id);
    if (itemIndex != -1) {
      items[itemIndex] = item;
    } else {
      items.add(item);
    }
    // Encode the items back to JSON and save to the file
    String updatedJson =
        jsonEncode(items.map((item) => item.toJson()).toList());
    await FileAccess.SaveDataFile(ItemFileString, updatedJson);
  }
}
