name: Server
publish_to: none # not intended for publication to pub.dev

environment:
  sdk: ^3.5.0

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  shared:
    path: ../shared
  mutex: ^3.1.0
  injector: ^4.0.0

dev_dependencies:
  http: ^1.2.2
  lints: ^5.0.0
  mockito: ^5.4.4
  test: ^1.25.8
  test_process: ^2.1.0
  build_runner: ^2.1.11